-- ============================================================
-- NextOri V1.2 — J'HÉSITE
-- Migration additive : ne supprime ni ne recrée les tables existantes.
-- PostgreSQL / Supabase
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- 1. Pistes personnelles
-- ------------------------------------------------------------
-- Une piste représente un métier OU une filière enregistré(e)
-- par un utilisateur. Le catalogue existant reste la source de vérité.

CREATE TABLE IF NOT EXISTS public.piste_utilisateur (
    id_piste integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user integer NOT NULL,
    type_piste varchar(20) NOT NULL,
    id_metier integer,
    id_filiere integer,
    date_ajout timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    statut varchar(20) DEFAULT 'active' NOT NULL,

    CONSTRAINT piste_utilisateur_type_check
        CHECK (type_piste IN ('metier', 'filiere')),

    CONSTRAINT piste_utilisateur_cible_check
        CHECK (
            (type_piste = 'metier' AND id_metier IS NOT NULL AND id_filiere IS NULL)
            OR
            (type_piste = 'filiere' AND id_filiere IS NOT NULL AND id_metier IS NULL)
        ),

    CONSTRAINT piste_utilisateur_statut_check
        CHECK (statut IN ('active', 'archive')),

    CONSTRAINT piste_utilisateur_user_fk
        FOREIGN KEY (id_user)
        REFERENCES public.utilisateur(id_user)
        ON DELETE CASCADE,

    CONSTRAINT piste_utilisateur_metier_fk
        FOREIGN KEY (id_metier)
        REFERENCES public.metier(id_metier)
        ON DELETE CASCADE,

    CONSTRAINT piste_utilisateur_filiere_fk
        FOREIGN KEY (id_filiere)
        REFERENCES public.filiere(id_filiere)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_piste_user_metier
    ON public.piste_utilisateur (id_user, id_metier)
    WHERE id_metier IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_piste_user_filiere
    ON public.piste_utilisateur (id_user, id_filiere)
    WHERE id_filiere IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_piste_utilisateur_user
    ON public.piste_utilisateur (id_user, statut, date_ajout DESC);


-- ------------------------------------------------------------
-- 2. Analyse d'une session J'HÉSITE
-- ------------------------------------------------------------
-- On réutilise hesitation_test comme session.
-- Aucune duplication du RIASEC : id_test_riasec pointe vers
-- le test actif utilisé au moment de l'analyse.

CREATE TABLE IF NOT EXISTS public.hesitation_analyse (
    id_analyse integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hesitation_test integer NOT NULL,
    id_test_riasec integer,
    id_piste_dominante integer,
    version_moteur varchar(30) NOT NULL DEFAULT 'v1.2.0',
    niveau_confiance numeric(5,2),
    synthese text,
    date_analyse timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT hesitation_analyse_test_unique
        UNIQUE (id_hesitation_test),

    CONSTRAINT hesitation_analyse_test_fk
        FOREIGN KEY (id_hesitation_test)
        REFERENCES public.hesitation_test(id_hesitation_test)
        ON DELETE CASCADE,

    CONSTRAINT hesitation_analyse_riasec_fk
        FOREIGN KEY (id_test_riasec)
        REFERENCES public.test_riasec(id_test)
        ON DELETE SET NULL,

    CONSTRAINT hesitation_analyse_piste_fk
        FOREIGN KEY (id_piste_dominante)
        REFERENCES public.piste_utilisateur(id_piste)
        ON DELETE SET NULL,

    CONSTRAINT hesitation_analyse_confiance_check
        CHECK (
            niveau_confiance IS NULL
            OR (niveau_confiance >= 0 AND niveau_confiance <= 100)
        )
);

CREATE INDEX IF NOT EXISTS idx_hesitation_analyse_riasec
    ON public.hesitation_analyse (id_test_riasec);

CREATE INDEX IF NOT EXISTS idx_hesitation_analyse_date
    ON public.hesitation_analyse (date_analyse DESC);


-- ------------------------------------------------------------
-- 3. Résultats détaillés par piste
-- ------------------------------------------------------------
-- On conserve les dimensions séparément.
-- Aucun "score magique" ne doit être la seule explication.

CREATE TABLE IF NOT EXISTS public.hesitation_analyse_piste (
    id_analyse_piste integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_analyse integer NOT NULL,
    id_piste integer NOT NULL,

    score_riasec numeric(6,2),
    score_criteres numeric(6,2),
    score_convergence numeric(6,2),
    score_information numeric(6,2),
    score_differenciation numeric(6,2),
    score_global numeric(6,2),

    rang integer,
    niveau_confiance numeric(5,2),

    position varchar(30) DEFAULT 'a_verifier' NOT NULL,

    raisons jsonb DEFAULT '[]'::jsonb NOT NULL,
    points_vigilance jsonb DEFAULT '[]'::jsonb NOT NULL,
    prochaines_etapes jsonb DEFAULT '[]'::jsonb NOT NULL,

    -- Snapshot des variables réellement utilisées.
    -- Utile pour audit, reproductibilité et futur ML.
    features_snapshot jsonb DEFAULT '{}'::jsonb NOT NULL,

    CONSTRAINT hesitation_analyse_piste_unique
        UNIQUE (id_analyse, id_piste),

    CONSTRAINT hesitation_analyse_piste_analyse_fk
        FOREIGN KEY (id_analyse)
        REFERENCES public.hesitation_analyse(id_analyse)
        ON DELETE CASCADE,

    CONSTRAINT hesitation_analyse_piste_piste_fk
        FOREIGN KEY (id_piste)
        REFERENCES public.piste_utilisateur(id_piste)
        ON DELETE CASCADE,

    CONSTRAINT hesitation_analyse_piste_position_check
        CHECK (
            position IN ('dominante', 'forte', 'proche', 'a_verifier')
        ),

    CONSTRAINT hesitation_analyse_piste_scores_check
        CHECK (
            (score_riasec IS NULL OR score_riasec BETWEEN 0 AND 100)
            AND (score_criteres IS NULL OR score_criteres BETWEEN 0 AND 100)
            AND (score_convergence IS NULL OR score_convergence BETWEEN 0 AND 100)
            AND (score_information IS NULL OR score_information BETWEEN 0 AND 100)
            AND (score_differenciation IS NULL OR score_differenciation BETWEEN 0 AND 100)
            AND (score_global IS NULL OR score_global BETWEEN 0 AND 100)
            AND (niveau_confiance IS NULL OR niveau_confiance BETWEEN 0 AND 100)
        )
);

CREATE INDEX IF NOT EXISTS idx_hesitation_analyse_piste_analyse
    ON public.hesitation_analyse_piste (id_analyse);

CREATE INDEX IF NOT EXISTS idx_hesitation_analyse_piste_position
    ON public.hesitation_analyse_piste (position);


-- ------------------------------------------------------------
-- 4. Événements structurés pour l'apprentissage futur
-- ------------------------------------------------------------
-- historique reste conservé pour l'application.
-- Cette table sert aux événements décisionnels structurés.

CREATE TABLE IF NOT EXISTS public.hesitation_evenement (
    id_evenement bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user integer NOT NULL,
    id_piste integer,
    id_hesitation_test integer,
    type_evenement varchar(50) NOT NULL,
    date_evenement timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    contexte jsonb DEFAULT '{}'::jsonb NOT NULL,

    CONSTRAINT hesitation_evenement_user_fk
        FOREIGN KEY (id_user)
        REFERENCES public.utilisateur(id_user)
        ON DELETE CASCADE,

    CONSTRAINT hesitation_evenement_piste_fk
        FOREIGN KEY (id_piste)
        REFERENCES public.piste_utilisateur(id_piste)
        ON DELETE SET NULL,

    CONSTRAINT hesitation_evenement_test_fk
        FOREIGN KEY (id_hesitation_test)
        REFERENCES public.hesitation_test(id_hesitation_test)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_hesitation_evenement_user_date
    ON public.hesitation_evenement (id_user, date_evenement DESC);

CREATE INDEX IF NOT EXISTS idx_hesitation_evenement_type
    ON public.hesitation_evenement (type_evenement);

CREATE INDEX IF NOT EXISTS idx_hesitation_evenement_piste
    ON public.hesitation_evenement (id_piste);


-- ------------------------------------------------------------
-- 5. Sécurisation légère des options d'une session
-- ------------------------------------------------------------
-- hesitation_option existe déjà et permet déjà de stocker
-- un métier OU une filière. On ne la remplace pas.

CREATE UNIQUE INDEX IF NOT EXISTS uq_hesitation_option_test_metier
    ON public.hesitation_option (id_hesitation_test, id_metier)
    WHERE id_metier IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_hesitation_option_test_filiere
    ON public.hesitation_option (id_hesitation_test, id_filiere)
    WHERE id_filiere IS NOT NULL;


-- ------------------------------------------------------------
-- 6. Version du moteur
-- ------------------------------------------------------------
-- Pas de modification de données existantes.
-- La version est enregistrée dans hesitation_analyse.

COMMIT;
